# PL & EN
language: "EN"

allowed_commands_before_login:
  - "/login"
  - "/register"

discord-link: "https://discord.gg/invite/123"

no_permission_message: "&cYou don't have permission to execute this command!"